export type FrameState = {
  method: string;
  pc: string;
  locals: string[];
  stack: string[];
  dynamicLink: string;
  returnAddress: string;
  exceptionTable: string;
};

export type ExecutionStep = {
  id: string;
  titleKey: string;
  bytecode: string;
  sourceLine: string;
  sourceLineIndex: number;
  bytecodeLine: string;
  bytecodeLineIndex: number;
  stack: FrameState[];
};

export const sourceLines = [
  "class App {",
  "  static int staticField = 1;",
  "  int instanceField = 2;",
  "",
  "  public int method1() {",
  "    int m = 3;",
  "    int n = 4;",
  "    int k = m + n;",
  "    return k;",
  "  }",
  "",
  "  public void method2(int d) {",
  "    int i = method1();",
  "    int j = 5;",
  "    try {",
  "      int k = 6 / d;",
  "    } catch (Exception e) {",
  "      j = 7;",
  "      e.printStackTrace();",
  "    }",
  "  }",
  "",
  "  public static void main(String[] args) {",
  "    App obj = new App();",
  "    int d = Integer.parseInt(args[0]);",
  "    obj.method2(d);",
  "  }",
  "}",
];

export const bytecodeLines = [
  "<init>:",
  " 0:aload_0",
  " 1:invokespecial #1",
  " 4:aload_0",
  " 5:iconst_2",
  " 6:putfield #7",
  " 9:return",
  "",
  "method1:",
  " 0:iconst_3",
  " 1:istore_1",
  " 2:iconst_4",
  " 3:istore_2",
  " 4:iload_1",
  " 5:iload_2",
  " 6:iadd",
  " 7:istore_3",
  " 8:iload_3",
  " 9:ireturn",
  "",
  "method2:",
  " 0:aload_0",
  " 1:invokevirtual #13",
  " 4:istore_2",
  " 5:iconst_5",
  " 6:istore_3",
  " 7:bipush 6",
  " 9:iload_1",
  "10:idiv",
  "11:istore 4",
  "13:goto 26",
  "16:astore 4",
  "18:bipush 7",
  "20:istore_3",
  "21:aload 4",
  "23:invokevirtual #19",
  "26:return",
  "",
  "main:",
  " 0:new #8",
  " 3:dup",
  " 4:invokespecial #22",
  " 7:astore_1",
  " 8:aload_0",
  " 9:iconst_0",
  "10:aaload",
  "11:invokestatic #23",
  "14:istore_2",
  "15:aload_1",
  "16:iload_2",
  "17:invokevirtual #29",
  "20:return",
];

export const getOpcodeFromLine = (line: string) => {
  const trimmed = line.trim();
  if (!trimmed || trimmed.endsWith(":")) {
    return null;
  }
  const [, rest] = trimmed.split(":");
  if (!rest) {
    return null;
  }
  return rest.trim().split(/\s+/)[0];
};

export const executionStepsNormal: ExecutionStep[] = [
  {
    id: "main-0",
    titleKey: "stepTitles.main-0",
    bytecode: "main@0: new #8",
    sourceLine: "main: App obj = new App();",
    sourceLineIndex: 23,
    bytecodeLine: "0: new #8",
    bytecodeLineIndex: 39,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "0",
        locals: ["0: args"],
        stack: ["uninit App"],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "main-1",
    titleKey: "stepTitles.main-1",
    bytecode: "main@3: dup",
    sourceLine: "main: App obj = new App();",
    sourceLineIndex: 23,
    bytecodeLine: "3: dup",
    bytecodeLineIndex: 40,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "3",
        locals: ["0: args"],
        stack: ["uninit App", "uninit App"],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "main-2",
    titleKey: "stepTitles.main-2",
    bytecode: "main@4: invokespecial <init>",
    sourceLine: "main: App obj = new App();",
    sourceLineIndex: 23,
    bytecodeLine: "4: invokespecial #22",
    bytecodeLineIndex: 41,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "4",
        locals: ["0: args"],
        stack: ["uninit App"],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.<init>()",
        pc: "0",
        locals: ["0: this=uninit App"],
        stack: [],
        dynamicLink: "App.<init> -> CP",
        returnAddress: "return to main@7",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "init-0",
    titleKey: "stepTitles.init-0",
    bytecode: "<init>@0: aload_0",
    sourceLine: "App(): instanceField = 2;",
    sourceLineIndex: 2,
    bytecodeLine: "0: aload_0",
    bytecodeLineIndex: 1,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "4",
        locals: ["0: args"],
        stack: ["uninit App"],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.<init>()",
        pc: "0",
        locals: ["0: this=uninit App"],
        stack: ["this"],
        dynamicLink: "App.<init> -> CP",
        returnAddress: "return to main@7",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "init-1",
    titleKey: "stepTitles.init-1",
    bytecode: "<init>@1: invokespecial #1",
    sourceLine: "App(): instanceField = 2;",
    sourceLineIndex: 2,
    bytecodeLine: "1: invokespecial #1",
    bytecodeLineIndex: 2,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "4",
        locals: ["0: args"],
        stack: ["uninit App"],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.<init>()",
        pc: "1",
        locals: ["0: this=uninit App"],
        stack: [],
        dynamicLink: "App.<init> -> CP",
        returnAddress: "return to main@7",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "init-2",
    titleKey: "stepTitles.init-2",
    bytecode: "<init>@4: aload_0",
    sourceLine: "App(): instanceField = 2;",
    sourceLineIndex: 2,
    bytecodeLine: "4: aload_0",
    bytecodeLineIndex: 3,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "4",
        locals: ["0: args"],
        stack: ["uninit App"],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.<init>()",
        pc: "4",
        locals: ["0: this=uninit App"],
        stack: ["this"],
        dynamicLink: "App.<init> -> CP",
        returnAddress: "return to main@7",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "init-3",
    titleKey: "stepTitles.init-3",
    bytecode: "<init>@5: iconst_2",
    sourceLine: "App(): instanceField = 2;",
    sourceLineIndex: 2,
    bytecodeLine: "5: iconst_2",
    bytecodeLineIndex: 4,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "4",
        locals: ["0: args"],
        stack: ["uninit App"],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.<init>()",
        pc: "5",
        locals: ["0: this=uninit App"],
        stack: ["this", "2"],
        dynamicLink: "App.<init> -> CP",
        returnAddress: "return to main@7",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "init-4",
    titleKey: "stepTitles.init-4",
    bytecode: "<init>@6: putfield instanceField",
    sourceLine: "App(): instanceField = 2;",
    sourceLineIndex: 2,
    bytecodeLine: "6: putfield #7",
    bytecodeLineIndex: 5,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "4",
        locals: ["0: args"],
        stack: ["uninit App"],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.<init>()",
        pc: "6",
        locals: ["0: this=uninit App"],
        stack: [],
        dynamicLink: "App.<init> -> CP",
        returnAddress: "return to main@7",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "init-5",
    titleKey: "stepTitles.init-5",
    bytecode: "<init>@9: return",
    sourceLine: "App(): return",
    sourceLineIndex: 2,
    bytecodeLine: "9: return",
    bytecodeLineIndex: 6,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "7",
        locals: ["0: args"],
        stack: ["obj"],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "main-3",
    titleKey: "stepTitles.main-3",
    bytecode: "main@7: astore_1",
    sourceLine: "main: App obj = new App();",
    sourceLineIndex: 23,
    bytecodeLine: "7: astore_1",
    bytecodeLineIndex: 42,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "7",
        locals: ["0: args", "1: obj"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "main-4",
    titleKey: "stepTitles.main-4",
    bytecode: "main@8: aload_0",
    sourceLine: "main: int d = Integer.parseInt(args[0]);",
    sourceLineIndex: 24,
    bytecodeLine: "8: aload_0",
    bytecodeLineIndex: 43,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "8",
        locals: ["0: args", "1: obj"],
        stack: ["args"],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "main-5",
    titleKey: "stepTitles.main-5",
    bytecode: "main@9: iconst_0",
    sourceLine: "main: int d = Integer.parseInt(args[0]);",
    sourceLineIndex: 24,
    bytecodeLine: "9: iconst_0",
    bytecodeLineIndex: 44,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "9",
        locals: ["0: args", "1: obj"],
        stack: ["args", "0"],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "main-6",
    titleKey: "stepTitles.main-6",
    bytecode: "main@10: aaload",
    sourceLine: "main: int d = Integer.parseInt(args[0]);",
    sourceLineIndex: 24,
    bytecodeLine: "10: aaload",
    bytecodeLineIndex: 45,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "10",
        locals: ["0: args", "1: obj"],
        stack: ["args[0]"],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "main-7",
    titleKey: "stepTitles.main-7",
    bytecode: "main@11: invokestatic parseInt",
    sourceLine: "main: int d = Integer.parseInt(args[0]);",
    sourceLineIndex: 24,
    bytecodeLine: "11: invokestatic #23",
    bytecodeLineIndex: 46,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "11",
        locals: ["0: args", "1: obj"],
        stack: ["d"],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "main-8",
    titleKey: "stepTitles.main-8",
    bytecode: "main@14: istore_2",
    sourceLine: "main: int d = Integer.parseInt(args[0]);",
    sourceLineIndex: 24,
    bytecodeLine: "14: istore_2",
    bytecodeLineIndex: 47,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "14",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "main-9",
    titleKey: "stepTitles.main-9",
    bytecode: "main@15: aload_1",
    sourceLine: "main: obj.method2(d);",
    sourceLineIndex: 25,
    bytecodeLine: "15: aload_1",
    bytecodeLineIndex: 48,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "15",
        locals: ["0: args", "1: obj", "2: d"],
        stack: ["obj"],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "main-10",
    titleKey: "stepTitles.main-10",
    bytecode: "main@16: iload_2",
    sourceLine: "main: obj.method2(d);",
    sourceLineIndex: 25,
    bytecodeLine: "16: iload_2",
    bytecodeLineIndex: 49,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "16",
        locals: ["0: args", "1: obj", "2: d"],
        stack: ["obj", "d"],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "main-11",
    titleKey: "stepTitles.main-11",
    bytecode: "main@17: invokevirtual method2",
    sourceLine: "main: obj.method2(d);",
    sourceLineIndex: 25,
    bytecodeLine: "17: invokevirtual #29",
    bytecodeLineIndex: 50,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "0",
        locals: ["0: this=obj", "1: d"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2-0",
    titleKey: "stepTitles.m2-0",
    bytecode: "method2@0: aload_0",
    sourceLine: "method2: int i = method1();",
    sourceLineIndex: 12,
    bytecodeLine: "0: aload_0",
    bytecodeLineIndex: 21,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "0",
        locals: ["0: this=obj", "1: d"],
        stack: ["this"],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2-1",
    titleKey: "stepTitles.m2-1",
    bytecode: "method2@1: invokevirtual method1",
    sourceLine: "method2: int i = method1();",
    sourceLineIndex: 12,
    bytecodeLine: "1: invokevirtual #13",
    bytecodeLineIndex: 22,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "1",
        locals: ["0: this=obj", "1: d"],
        stack: ["this"],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
      {
        method: "App.method1()",
        pc: "0",
        locals: ["0: this=obj"],
        stack: [],
        dynamicLink: "App.method1 -> CP",
        returnAddress: "return to method2@4",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "m1-0",
    titleKey: "stepTitles.m1-0",
    bytecode: "method1@0: iconst_3",
    sourceLine: "method1: int m = 3;",
    sourceLineIndex: 5,
    bytecodeLine: "0: iconst_3",
    bytecodeLineIndex: 9,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "1",
        locals: ["0: this=obj", "1: d"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
      {
        method: "App.method1()",
        pc: "0",
        locals: ["0: this=obj"],
        stack: ["3"],
        dynamicLink: "App.method1 -> CP",
        returnAddress: "return to method2@4",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "m1-1",
    titleKey: "stepTitles.m1-1",
    bytecode: "method1@1: istore_1",
    sourceLine: "method1: int m = 3;",
    sourceLineIndex: 5,
    bytecodeLine: "1: istore_1",
    bytecodeLineIndex: 10,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "1",
        locals: ["0: this=obj", "1: d"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
      {
        method: "App.method1()",
        pc: "1",
        locals: ["0: this=obj", "1: m=3"],
        stack: [],
        dynamicLink: "App.method1 -> CP",
        returnAddress: "return to method2@4",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "m1-2",
    titleKey: "stepTitles.m1-2",
    bytecode: "method1@2: iconst_4",
    sourceLine: "method1: int n = 4;",
    sourceLineIndex: 6,
    bytecodeLine: "2: iconst_4",
    bytecodeLineIndex: 11,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "1",
        locals: ["0: this=obj", "1: d"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
      {
        method: "App.method1()",
        pc: "2",
        locals: ["0: this=obj", "1: m=3"],
        stack: ["4"],
        dynamicLink: "App.method1 -> CP",
        returnAddress: "return to method2@4",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "m1-3",
    titleKey: "stepTitles.m1-3",
    bytecode: "method1@3: istore_2",
    sourceLine: "method1: int n = 4;",
    sourceLineIndex: 6,
    bytecodeLine: "3: istore_2",
    bytecodeLineIndex: 12,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "1",
        locals: ["0: this=obj", "1: d"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
      {
        method: "App.method1()",
        pc: "3",
        locals: ["0: this=obj", "1: m=3", "2: n=4"],
        stack: [],
        dynamicLink: "App.method1 -> CP",
        returnAddress: "return to method2@4",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "m1-4",
    titleKey: "stepTitles.m1-4",
    bytecode: "method1@4: iload_1",
    sourceLine: "method1: int k = m + n;",
    sourceLineIndex: 7,
    bytecodeLine: "4: iload_1",
    bytecodeLineIndex: 13,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "1",
        locals: ["0: this=obj", "1: d"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
      {
        method: "App.method1()",
        pc: "4",
        locals: ["0: this=obj", "1: m=3", "2: n=4"],
        stack: ["m=3"],
        dynamicLink: "App.method1 -> CP",
        returnAddress: "return to method2@4",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "m1-5",
    titleKey: "stepTitles.m1-5",
    bytecode: "method1@5: iload_2",
    sourceLine: "method1: int k = m + n;",
    sourceLineIndex: 7,
    bytecodeLine: "5: iload_2",
    bytecodeLineIndex: 14,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "1",
        locals: ["0: this=obj", "1: d"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
      {
        method: "App.method1()",
        pc: "5",
        locals: ["0: this=obj", "1: m=3", "2: n=4"],
        stack: ["m=3", "n=4"],
        dynamicLink: "App.method1 -> CP",
        returnAddress: "return to method2@4",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "m1-6",
    titleKey: "stepTitles.m1-6",
    bytecode: "method1@6: iadd",
    sourceLine: "method1: int k = m + n;",
    sourceLineIndex: 7,
    bytecodeLine: "6: iadd",
    bytecodeLineIndex: 15,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "1",
        locals: ["0: this=obj", "1: d"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
      {
        method: "App.method1()",
        pc: "6",
        locals: ["0: this=obj", "1: m=3", "2: n=4"],
        stack: ["7"],
        dynamicLink: "App.method1 -> CP",
        returnAddress: "return to method2@4",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "m1-7",
    titleKey: "stepTitles.m1-7",
    bytecode: "method1@7: istore_3",
    sourceLine: "method1: int k = m + n;",
    sourceLineIndex: 7,
    bytecodeLine: "7: istore_3",
    bytecodeLineIndex: 16,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "1",
        locals: ["0: this=obj", "1: d"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
      {
        method: "App.method1()",
        pc: "7",
        locals: ["0: this=obj", "1: m=3", "2: n=4", "3: k=7"],
        stack: [],
        dynamicLink: "App.method1 -> CP",
        returnAddress: "return to method2@4",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "m1-8",
    titleKey: "stepTitles.m1-8",
    bytecode: "method1@8: iload_3",
    sourceLine: "method1: return k;",
    sourceLineIndex: 8,
    bytecodeLine: "8: iload_3",
    bytecodeLineIndex: 17,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "1",
        locals: ["0: this=obj", "1: d"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
      {
        method: "App.method1()",
        pc: "8",
        locals: ["0: this=obj", "1: m=3", "2: n=4", "3: k=7"],
        stack: ["7"],
        dynamicLink: "App.method1 -> CP",
        returnAddress: "return to method2@4",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "m1-9",
    titleKey: "stepTitles.m1-9",
    bytecode: "method1@9: ireturn",
    sourceLine: "method1: return k;",
    sourceLineIndex: 8,
    bytecodeLine: "9: ireturn",
    bytecodeLineIndex: 18,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "4",
        locals: ["0: this=obj", "1: d"],
        stack: ["7"],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2-2",
    titleKey: "stepTitles.m2-2",
    bytecode: "method2@4: istore_2",
    sourceLine: "method2: int i = method1();",
    sourceLineIndex: 12,
    bytecodeLine: "4: istore_2",
    bytecodeLineIndex: 23,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "4",
        locals: ["0: this=obj", "1: d", "2: i=7"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2-3",
    titleKey: "stepTitles.m2-3",
    bytecode: "method2@5: iconst_5",
    sourceLine: "method2: int j = 5;",
    sourceLineIndex: 13,
    bytecodeLine: "5: iconst_5",
    bytecodeLineIndex: 24,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "5",
        locals: ["0: this=obj", "1: d", "2: i=7"],
        stack: ["5"],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2-4",
    titleKey: "stepTitles.m2-4",
    bytecode: "method2@6: istore_3",
    sourceLine: "method2: int j = 5;",
    sourceLineIndex: 13,
    bytecodeLine: "6: istore_3",
    bytecodeLineIndex: 25,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "6",
        locals: ["0: this=obj", "1: d", "2: i=7", "3: j=5"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2-5",
    titleKey: "stepTitles.m2-5",
    bytecode: "method2@7: bipush 6",
    sourceLine: "method2: int k = 6 / d;",
    sourceLineIndex: 15,
    bytecodeLine: "7: bipush 6",
    bytecodeLineIndex: 26,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "7",
        locals: ["0: this=obj", "1: d", "2: i=7", "3: j=5"],
        stack: ["6"],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2-6",
    titleKey: "stepTitles.m2-6",
    bytecode: "method2@9: iload_1",
    sourceLine: "method2: int k = 6 / d;",
    sourceLineIndex: 15,
    bytecodeLine: "9: iload_1",
    bytecodeLineIndex: 27,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "9",
        locals: ["0: this=obj", "1: d", "2: i=7", "3: j=5"],
        stack: ["6", "d"],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2-7",
    titleKey: "stepTitles.m2-7",
    bytecode: "method2@10: idiv",
    sourceLine: "method2: int k = 6 / d;",
    sourceLineIndex: 15,
    bytecodeLine: "10: idiv",
    bytecodeLineIndex: 28,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "10",
        locals: ["0: this=obj", "1: d", "2: i=7", "3: j=5"],
        stack: ["6/d"],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2-8",
    titleKey: "stepTitles.m2-8",
    bytecode: "method2@11: istore 4",
    sourceLine: "method2: int k = 6 / d;",
    sourceLineIndex: 15,
    bytecodeLine: "11: istore 4",
    bytecodeLineIndex: 29,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "11",
        locals: ["0: this=obj", "1: d", "2: i=7", "3: j=5", "4: k=6/d"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2-9",
    titleKey: "stepTitles.m2-9",
    bytecode: "method2@13: goto 26",
    sourceLine: "method2: return",
    sourceLineIndex: 19,
    bytecodeLine: "13: goto 26",
    bytecodeLineIndex: 30,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "13",
        locals: ["0: this=obj", "1: d", "2: i=7", "3: j=5", "4: k=6/d"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2-10",
    titleKey: "stepTitles.m2-10",
    bytecode: "method2@26: return",
    sourceLine: "method2: return",
    sourceLineIndex: 19,
    bytecodeLine: "26: return",
    bytecodeLineIndex: 36,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "20",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "main-12",
    titleKey: "stepTitles.main-12",
    bytecode: "main@20: return",
    sourceLine: "main: return",
    sourceLineIndex: 25,
    bytecodeLine: "20: return",
    bytecodeLineIndex: 51,
    stack: [],
  },
];

export const executionStepsException: ExecutionStep[] = [
  ...executionStepsNormal.slice(
    0,
    executionStepsNormal.findIndex((step) => step.id === "m2-7")
  ),
  {
    id: "m2x-0",
    titleKey: "stepTitles.m2x-0",
    bytecode: "method2@10: idiv",
    sourceLine: "method2: int k = 6 / d;",
    sourceLineIndex: 15,
    bytecodeLine: "10: idiv",
    bytecodeLineIndex: 28,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d=0"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "10",
        locals: ["0: this=obj", "1: d=0", "2: i=7", "3: j=5"],
        stack: ["6", "0", "Exception"],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2x-1",
    titleKey: "stepTitles.m2x-1",
    bytecode: "method2@16: astore 4",
    sourceLine: "method2: catch (Exception e)",
    sourceLineIndex: 16,
    bytecodeLine: "16: astore 4",
    bytecodeLineIndex: 31,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d=0"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "16",
        locals: ["0: this=obj", "1: d=0", "2: i=7", "3: j=5", "4: e"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2x-2",
    titleKey: "stepTitles.m2x-2",
    bytecode: "method2@18: bipush 7",
    sourceLine: "method2: j = 7;",
    sourceLineIndex: 17,
    bytecodeLine: "18: bipush 7",
    bytecodeLineIndex: 32,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d=0"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "18",
        locals: ["0: this=obj", "1: d=0", "2: i=7", "3: j=5", "4: e"],
        stack: ["7"],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2x-3",
    titleKey: "stepTitles.m2x-3",
    bytecode: "method2@20: istore_3",
    sourceLine: "method2: j = 7;",
    sourceLineIndex: 17,
    bytecodeLine: "20: istore_3",
    bytecodeLineIndex: 33,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d=0"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "20",
        locals: ["0: this=obj", "1: d=0", "2: i=7", "3: j=7", "4: e"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2x-4",
    titleKey: "stepTitles.m2x-4",
    bytecode: "method2@21: aload 4",
    sourceLine: "method2: e.printStackTrace();",
    sourceLineIndex: 18,
    bytecodeLine: "21: aload 4",
    bytecodeLineIndex: 34,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d=0"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "21",
        locals: ["0: this=obj", "1: d=0", "2: i=7", "3: j=7", "4: e"],
        stack: ["e"],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2x-5",
    titleKey: "stepTitles.m2x-5",
    bytecode: "method2@23: invokevirtual printStackTrace",
    sourceLine: "method2: e.printStackTrace();",
    sourceLineIndex: 18,
    bytecodeLine: "23: invokevirtual #19",
    bytecodeLineIndex: 35,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d=0"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "23",
        locals: ["0: this=obj", "1: d=0", "2: i=7", "3: j=7", "4: e"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2x-6",
    titleKey: "stepTitles.m2x-6",
    bytecode: "method2@26: return",
    sourceLine: "method2: return",
    sourceLineIndex: 19,
    bytecodeLine: "26: return",
    bytecodeLineIndex: 36,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "20",
        locals: ["0: args", "1: obj", "2: d=0"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "main-12x",
    titleKey: "stepTitles.main-12x",
    bytecode: "main@20: return",
    sourceLine: "main: return",
    sourceLineIndex: 25,
    bytecodeLine: "20: return",
    bytecodeLineIndex: 51,
    stack: [],
  },
];
