export type FrameState = {
  method: string;
  pc: string;
  locals: string[];
  stack: string[];
  dynamicLink: string;
  returnAddress: string;
  exceptionTable: string;
};

export type ExecutionStep = {
  id: string;
  title: string;
  bytecode: string;
  sourceLine: string;
  sourceLineIndex: number;
  bytecodeLine: string;
  bytecodeLineIndex: number;
  stack: FrameState[];
};

type DetailTab = {
  id: string;
  label: string;
  items?: string[];
  diagram?: string[];
};

type RuntimeAreaDetail = {
  summary: string;
  tabs: DetailTab[];
};

export const runtimeAreas = [
  {
    id: "heap",
    name: "Heap",
    stored: "对象实例、数组",
    ownership: "线程共享",
    notes: ["对象分配的主要区域", "回收由 GC 驱动"],
    scopeTag: "Shared",
  },
  {
    id: "stack",
    name: "Java Stack",
    stored: "栈帧：局部变量表、操作数栈、返回地址",
    ownership: "线程私有",
    notes: ["方法调用入栈/出栈", "栈深度影响稳定性"],
    scopeTag: "Private",
  },
  {
    id: "method-area",
    name: "Method Area",
    stored: "类元数据、常量池、静态变量",
    ownership: "线程共享",
    notes: ["类级信息集中管理", "可被回收/卸载"],
    scopeTag: "Shared",
  },
  {
    id: "pc",
    name: "PC Register",
    stored: "下一条字节码指令地址",
    ownership: "线程私有",
    notes: ["执行后更新", "线程切换可恢复"],
    scopeTag: "Private",
  },
  {
    id: "native-stack",
    name: "Native Method Stack",
    stored: "本地方法栈帧",
    ownership: "线程私有",
    notes: ["JNI 调用支撑", "与 OS 栈关联"],
    scopeTag: "Private",
  },
];

export const runtimeAreaDetails: Record<string, RuntimeAreaDetail> = {
  heap: {
    summary: "线程共享的主要内存区，负责对象与数组的分配与回收。",
    tabs: [
      {
        id: "overview",
        label: "概览",
        items: [
          "分代管理：新生代/老年代，GC 主要发生在新生代。",
          "字符串常量池：JDK 7 起迁移到堆内，与方法区分离。",
          "对象分配：TLAB 优化线程内分配，失败后走共享分配。",
        ],
      },
      {
        id: "structure",
        label: "结构",
        diagram: [
          "Young Gen",
          "  ├─ Eden",
          "  ├─ S0 (From)",
          "  └─ S1 (To)",
          "Old Gen",
          "  └─ Tenured",
        ],
        items: ["对象优先进入 Eden，存活对象在 Survivor 之间复制。"],
      },
      {
        id: "versions",
        label: "版本差异",
        items: [
          "JDK 6/7: 字符串常量池在永久代/方法区。",
          "JDK 7+: 字符串常量池迁移到堆，减少永久代压力。",
        ],
      },
      {
        id: "config",
        label: "配置",
        items: [
          "-Xms/-Xmx：堆初始/最大大小",
          "-Xmn：新生代大小",
          "-XX:NewRatio：新生代与老年代比例",
          "-XX:SurvivorRatio：Eden 与 Survivor 比例",
          "-XX:MaxTenuringThreshold：晋升年龄",
        ],
      },
      {
        id: "exceptions",
        label: "异常",
        items: [
          "OutOfMemoryError: Java heap space",
          "GC overhead limit exceeded",
        ],
      },
    ],
  },
  "method-area": {
    summary: "方法区是 JVM 规范的概念，存储类元数据与运行时常量。",
    tabs: [
      {
        id: "overview",
        label: "概览",
        items: [
          "存储：类元数据、运行时常量池、静态变量、即时编译代码。",
          "与堆不同：主要存放类级别数据，线程共享。",
        ],
      },
      {
        id: "versions",
        label: "版本实现",
        items: [
          "PermGen (<= JDK 7): 位于堆内，易 OOM，大小固定。",
          "Metaspace (JDK 8+): 位于本地内存，按需扩展。",
          "替换原因：类元数据大小难预测，PermGen 调优成本高。",
        ],
      },
      {
        id: "structure",
        label: "简图",
        diagram: [
          "Method Area",
          "  ├─ Class Metadata",
          "  ├─ Runtime Constant Pool",
          "  └─ Static Variables",
          "",
          "JDK 8+: Metaspace (Native Memory)",
        ],
      },
      {
        id: "config",
        label: "配置",
        items: [
          "-XX:MetaspaceSize/-XX:MaxMetaspaceSize (JDK 8+)",
          "-XX:PermSize/-XX:MaxPermSize (JDK 7-)",
        ],
      },
      {
        id: "exceptions",
        label: "异常",
        items: ["OutOfMemoryError: Metaspace", "PermGen space (JDK 7-)"],
      },
    ],
  },
  pc: {
    summary: "线程私有寄存器，保存下一条将执行的字节码地址。",
    tabs: [
      {
        id: "overview",
        label: "说明",
        items: [
          "执行字节码后会更新，线程切换可恢复执行。",
          "执行本地方法时，PC 值不定义。",
        ],
      },
    ],
  },
  stack: {
    summary: "线程私有，保存方法调用时创建的栈帧。",
    tabs: [
      {
        id: "overview",
        label: "栈帧内容",
        items: [
          "局部变量表：保存方法参数与局部变量。",
          "操作数栈：执行指令时的临时数据区。",
          "动态链接：指向运行时常量池的方法引用。",
          "方法出口：正常/异常返回地址。",
          "异常表：catch 处理器区间与跳转位置。",
        ],
      },
      {
        id: "structure",
        label: "简图",
        diagram: [
          "Stack (Thread)",
          "  ├─ Frame N",
          "  │   ├─ Local Vars",
          "  │   ├─ Operand Stack",
          "  │   ├─ Dynamic Link",
          "  │   └─ Return/Exception",
          "  └─ Frame 1",
        ],
      },
      {
        id: "config",
        label: "配置",
        items: ["-Xss：每个线程栈大小"],
      },
      {
        id: "exceptions",
        label: "异常",
        items: ["StackOverflowError", "OutOfMemoryError: unable to create new native thread"],
      },
    ],
  },
  "native-stack": {
    summary: "为 JVM 调用本地方法（JNI）提供栈空间。",
    tabs: [
      {
        id: "overview",
        label: "用途",
        items: [
          "执行 C/C++ 等本地方法调用。",
          "与 OS 线程栈关联，具体实现依赖 JVM 与平台。",
        ],
      },
      {
        id: "config",
        label: "配置",
        items: ["-Xss：影响本地方法栈大小（依实现）"],
      },
      {
        id: "exceptions",
        label: "异常",
        items: ["StackOverflowError", "OutOfMemoryError"],
      },
    ],
  },
};

export const flowSteps = [
  "Java 源码编译成 .class 字节码",
  "类加载器完成加载、验证、准备、解析、初始化",
  "运行时数据区为代码执行提供内存与元数据",
  "执行引擎解释/编译字节码并协同 GC",
  "JNI 调用本地库与 OS 交互",
];

export const exampleMappings = [
  {
    label: "A 类元数据",
    location: "Method Area",
    detail: "类结构、方法字节码、常量池",
  },
  {
    label: "static int count",
    location: "Method Area",
    detail: "静态变量，类级共享",
  },
  {
    label: "new A() 对象",
    location: "Heap",
    detail: "实例数据 + 对象头",
  },
  {
    label: "int x / int y",
    location: "Java Stack",
    detail: "局部变量表",
  },
  {
    label: "obj 引用",
    location: "Java Stack",
    detail: "指向堆中对象的引用",
  },
  {
    label: "字节码指令位置",
    location: "PC Register",
    detail: "记录当前线程执行到哪一行",
  },
];

export const sourceLines = [
  "class App {",
  "  static int staticField = 1;",
  "  int instanceField = 2;",
  "",
  "  public int method1() {",
  "    int m = 3;",
  "    int n = 4;",
  "    int k = m + n;",
  "    return k;",
  "  }",
  "",
  "  public void method2(int d) {",
  "    int i = method1();",
  "    int j = 5;",
  "    try {",
  "      int k = 6 / d;",
  "    } catch (Exception e) {",
  "      j = 7;",
  "      e.printStackTrace();",
  "    }",
  "  }",
  "",
  "  public static void main(String[] args) {",
  "    App obj = new App();",
  "    int d = Integer.parseInt(args[0]);",
  "    obj.method2(d);",
  "  }",
  "}",
];

export const bytecodeLines = [
  "<init>:",
  " 0:aload_0",
  " 1:invokespecial #1",
  " 4:aload_0",
  " 5:iconst_2",
  " 6:putfield #7",
  " 9:return",
  "",
  "method1:",
  " 0:iconst_3",
  " 1:istore_1",
  " 2:iconst_4",
  " 3:istore_2",
  " 4:iload_1",
  " 5:iload_2",
  " 6:iadd",
  " 7:istore_3",
  " 8:iload_3",
  " 9:ireturn",
  "",
  "method2:",
  " 0:aload_0",
  " 1:invokevirtual #13",
  " 4:istore_2",
  " 5:iconst_5",
  " 6:istore_3",
  " 7:bipush 6",
  " 9:iload_1",
  "10:idiv",
  "11:istore 4",
  "13:goto 26",
  "16:astore 4",
  "18:bipush 7",
  "20:istore_3",
  "21:aload 4",
  "23:invokevirtual #19",
  "26:return",
  "",
  "main:",
  " 0:new #8",
  " 3:dup",
  " 4:invokespecial #22",
  " 7:astore_1",
  " 8:aload_0",
  " 9:iconst_0",
  "10:aaload",
  "11:invokestatic #23",
  "14:istore_2",
  "15:aload_1",
  "16:iload_2",
  "17:invokevirtual #29",
  "20:return",
];

const opcodeDescriptions: Record<string, string> = {
  new: "在堆中分配对象内存，压入未初始化引用。",
  dup: "复制操作数栈顶元素。",
  invokespecial: "调用实例初始化方法或私有方法。",
  invokevirtual: "调用虚方法（动态分派）。",
  invokestatic: "调用静态方法。",
  aload_0: "将局部变量表 slot0 引用压栈。",
  aload_1: "将局部变量表 slot1 引用压栈。",
  aload: "将指定 slot 的引用压栈。",
  iload_1: "将局部变量表 slot1 int 压栈。",
  iload_2: "将局部变量表 slot2 int 压栈。",
  iconst_0: "将 int 常量 0 压栈。",
  iconst_2: "将 int 常量 2 压栈。",
  iconst_3: "将 int 常量 3 压栈。",
  iconst_4: "将 int 常量 4 压栈。",
  iconst_5: "将 int 常量 5 压栈。",
  bipush: "将一个字节常量压栈。",
  putfield: "将栈顶值写入对象实例字段。",
  putstatic: "将栈顶值写入类静态字段。",
  istore_1: "将栈顶 int 保存到 slot1。",
  istore_2: "将栈顶 int 保存到 slot2。",
  istore_3: "将栈顶 int 保存到 slot3。",
  istore: "将栈顶 int 保存到指定 slot。",
  iload_3: "将局部变量表 slot3 int 压栈。",
  iadd: "弹出两个 int 相加后压栈。",
  idiv: "弹出两个 int 相除后压栈（可能抛异常）。",
  aaload: "从引用数组中取元素并压栈。",
  astore: "将栈顶引用保存到指定 slot。",
  return: "从 void 方法返回。",
  ireturn: "返回 int 并弹出当前栈帧。",
  goto: "无条件跳转到指定偏移。",
};

export const getOpcodeFromLine = (line: string) => {
  const trimmed = line.trim();
  if (!trimmed || trimmed.endsWith(":")) {
    return null;
  }
  const [, rest] = trimmed.split(":");
  if (!rest) {
    return null;
  }
  return rest.trim().split(/\s+/)[0];
};

export const getBytecodeTooltip = (line: string) => {
  const opcode = getOpcodeFromLine(line);
  if (!opcode) {
    return line;
  }
  const desc = opcodeDescriptions[opcode];
  if (!desc) {
    return `${line}\n指令: ${opcode}`;
  }
  return `${line}\n指令: ${opcode}\n含义: ${desc}`;
};

export const executionStepsNormal: ExecutionStep[] = [
  {
    id: "main-0",
    title: "进入 main",
    bytecode: "main@0: new #8",
    sourceLine: "main: App obj = new App();",
    sourceLineIndex: 23,
    bytecodeLine: "0: new #8",
    bytecodeLineIndex: 39,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "0",
        locals: ["0: args"],
        stack: ["uninit App"],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "main-1",
    title: "复制栈顶引用",
    bytecode: "main@3: dup",
    sourceLine: "main: App obj = new App();",
    sourceLineIndex: 23,
    bytecodeLine: "3: dup",
    bytecodeLineIndex: 40,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "3",
        locals: ["0: args"],
        stack: ["uninit App", "uninit App"],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "main-2",
    title: "调用构造函数",
    bytecode: "main@4: invokespecial <init>",
    sourceLine: "main: App obj = new App();",
    sourceLineIndex: 23,
    bytecodeLine: "4: invokespecial #22",
    bytecodeLineIndex: 41,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "4",
        locals: ["0: args"],
        stack: ["uninit App"],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.<init>()",
        pc: "0",
        locals: ["0: this=uninit App"],
        stack: [],
        dynamicLink: "App.<init> -> CP",
        returnAddress: "return to main@7",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "init-0",
    title: "构造函数加载 this",
    bytecode: "<init>@0: aload_0",
    sourceLine: "App(): instanceField = 2;",
    sourceLineIndex: 2,
    bytecodeLine: "0: aload_0",
    bytecodeLineIndex: 1,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "4",
        locals: ["0: args"],
        stack: ["uninit App"],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.<init>()",
        pc: "0",
        locals: ["0: this=uninit App"],
        stack: ["this"],
        dynamicLink: "App.<init> -> CP",
        returnAddress: "return to main@7",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "init-1",
    title: "调用父类构造",
    bytecode: "<init>@1: invokespecial #1",
    sourceLine: "App(): instanceField = 2;",
    sourceLineIndex: 2,
    bytecodeLine: "1: invokespecial #1",
    bytecodeLineIndex: 2,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "4",
        locals: ["0: args"],
        stack: ["uninit App"],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.<init>()",
        pc: "1",
        locals: ["0: this=uninit App"],
        stack: [],
        dynamicLink: "App.<init> -> CP",
        returnAddress: "return to main@7",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "init-2",
    title: "再次加载 this",
    bytecode: "<init>@4: aload_0",
    sourceLine: "App(): instanceField = 2;",
    sourceLineIndex: 2,
    bytecodeLine: "4: aload_0",
    bytecodeLineIndex: 3,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "4",
        locals: ["0: args"],
        stack: ["uninit App"],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.<init>()",
        pc: "4",
        locals: ["0: this=uninit App"],
        stack: ["this"],
        dynamicLink: "App.<init> -> CP",
        returnAddress: "return to main@7",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "init-3",
    title: "压入常量 2",
    bytecode: "<init>@5: iconst_2",
    sourceLine: "App(): instanceField = 2;",
    sourceLineIndex: 2,
    bytecodeLine: "5: iconst_2",
    bytecodeLineIndex: 4,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "4",
        locals: ["0: args"],
        stack: ["uninit App"],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.<init>()",
        pc: "5",
        locals: ["0: this=uninit App"],
        stack: ["this", "2"],
        dynamicLink: "App.<init> -> CP",
        returnAddress: "return to main@7",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "init-4",
    title: "写入 instanceField",
    bytecode: "<init>@6: putfield instanceField",
    sourceLine: "App(): instanceField = 2;",
    sourceLineIndex: 2,
    bytecodeLine: "6: putfield #7",
    bytecodeLineIndex: 5,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "4",
        locals: ["0: args"],
        stack: ["uninit App"],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.<init>()",
        pc: "6",
        locals: ["0: this=uninit App"],
        stack: [],
        dynamicLink: "App.<init> -> CP",
        returnAddress: "return to main@7",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "init-5",
    title: "构造返回，弹栈",
    bytecode: "<init>@9: return",
    sourceLine: "App(): return",
    sourceLineIndex: 2,
    bytecodeLine: "9: return",
    bytecodeLineIndex: 6,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "7",
        locals: ["0: args"],
        stack: ["obj"],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "main-3",
    title: "保存对象引用",
    bytecode: "main@7: astore_1",
    sourceLine: "main: App obj = new App();",
    sourceLineIndex: 23,
    bytecodeLine: "7: astore_1",
    bytecodeLineIndex: 42,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "7",
        locals: ["0: args", "1: obj"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "main-4",
    title: "加载参数数组",
    bytecode: "main@8: aload_0",
    sourceLine: "main: int d = Integer.parseInt(args[0]);",
    sourceLineIndex: 24,
    bytecodeLine: "8: aload_0",
    bytecodeLineIndex: 43,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "8",
        locals: ["0: args", "1: obj"],
        stack: ["args"],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "main-5",
    title: "压入索引 0",
    bytecode: "main@9: iconst_0",
    sourceLine: "main: int d = Integer.parseInt(args[0]);",
    sourceLineIndex: 24,
    bytecodeLine: "9: iconst_0",
    bytecodeLineIndex: 44,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "9",
        locals: ["0: args", "1: obj"],
        stack: ["args", "0"],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "main-6",
    title: "读取 args[0]",
    bytecode: "main@10: aaload",
    sourceLine: "main: int d = Integer.parseInt(args[0]);",
    sourceLineIndex: 24,
    bytecodeLine: "10: aaload",
    bytecodeLineIndex: 45,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "10",
        locals: ["0: args", "1: obj"],
        stack: ["args[0]"],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "main-7",
    title: "parseInt 转换",
    bytecode: "main@11: invokestatic parseInt",
    sourceLine: "main: int d = Integer.parseInt(args[0]);",
    sourceLineIndex: 24,
    bytecodeLine: "11: invokestatic #23",
    bytecodeLineIndex: 46,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "11",
        locals: ["0: args", "1: obj"],
        stack: ["d"],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "main-8",
    title: "保存 d 到局部变量",
    bytecode: "main@14: istore_2",
    sourceLine: "main: int d = Integer.parseInt(args[0]);",
    sourceLineIndex: 24,
    bytecodeLine: "14: istore_2",
    bytecodeLineIndex: 47,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "14",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "main-9",
    title: "加载 obj 引用",
    bytecode: "main@15: aload_1",
    sourceLine: "main: obj.method2(d);",
    sourceLineIndex: 25,
    bytecodeLine: "15: aload_1",
    bytecodeLineIndex: 48,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "15",
        locals: ["0: args", "1: obj", "2: d"],
        stack: ["obj"],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "main-10",
    title: "加载参数 d",
    bytecode: "main@16: iload_2",
    sourceLine: "main: obj.method2(d);",
    sourceLineIndex: 25,
    bytecodeLine: "16: iload_2",
    bytecodeLineIndex: 49,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "16",
        locals: ["0: args", "1: obj", "2: d"],
        stack: ["obj", "d"],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "main-11",
    title: "调用 method2，压栈",
    bytecode: "main@17: invokevirtual method2",
    sourceLine: "main: obj.method2(d);",
    sourceLineIndex: 25,
    bytecodeLine: "17: invokevirtual #29",
    bytecodeLineIndex: 50,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "0",
        locals: ["0: this=obj", "1: d"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2-0",
    title: "加载 this",
    bytecode: "method2@0: aload_0",
    sourceLine: "method2: int i = method1();",
    sourceLineIndex: 12,
    bytecodeLine: "0: aload_0",
    bytecodeLineIndex: 21,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "0",
        locals: ["0: this=obj", "1: d"],
        stack: ["this"],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2-1",
    title: "调用 method1",
    bytecode: "method2@1: invokevirtual method1",
    sourceLine: "method2: int i = method1();",
    sourceLineIndex: 12,
    bytecodeLine: "1: invokevirtual #13",
    bytecodeLineIndex: 22,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "1",
        locals: ["0: this=obj", "1: d"],
        stack: ["this"],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
      {
        method: "App.method1()",
        pc: "0",
        locals: ["0: this=obj"],
        stack: [],
        dynamicLink: "App.method1 -> CP",
        returnAddress: "return to method2@4",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "m1-0",
    title: "压入常量 3",
    bytecode: "method1@0: iconst_3",
    sourceLine: "method1: int m = 3;",
    sourceLineIndex: 5,
    bytecodeLine: "0: iconst_3",
    bytecodeLineIndex: 9,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "1",
        locals: ["0: this=obj", "1: d"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
      {
        method: "App.method1()",
        pc: "0",
        locals: ["0: this=obj"],
        stack: ["3"],
        dynamicLink: "App.method1 -> CP",
        returnAddress: "return to method2@4",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "m1-1",
    title: "保存 m",
    bytecode: "method1@1: istore_1",
    sourceLine: "method1: int m = 3;",
    sourceLineIndex: 5,
    bytecodeLine: "1: istore_1",
    bytecodeLineIndex: 10,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "1",
        locals: ["0: this=obj", "1: d"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
      {
        method: "App.method1()",
        pc: "1",
        locals: ["0: this=obj", "1: m=3"],
        stack: [],
        dynamicLink: "App.method1 -> CP",
        returnAddress: "return to method2@4",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "m1-2",
    title: "压入常量 4",
    bytecode: "method1@2: iconst_4",
    sourceLine: "method1: int n = 4;",
    sourceLineIndex: 6,
    bytecodeLine: "2: iconst_4",
    bytecodeLineIndex: 11,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "1",
        locals: ["0: this=obj", "1: d"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
      {
        method: "App.method1()",
        pc: "2",
        locals: ["0: this=obj", "1: m=3"],
        stack: ["4"],
        dynamicLink: "App.method1 -> CP",
        returnAddress: "return to method2@4",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "m1-3",
    title: "保存 n",
    bytecode: "method1@3: istore_2",
    sourceLine: "method1: int n = 4;",
    sourceLineIndex: 6,
    bytecodeLine: "3: istore_2",
    bytecodeLineIndex: 12,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "1",
        locals: ["0: this=obj", "1: d"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
      {
        method: "App.method1()",
        pc: "3",
        locals: ["0: this=obj", "1: m=3", "2: n=4"],
        stack: [],
        dynamicLink: "App.method1 -> CP",
        returnAddress: "return to method2@4",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "m1-4",
    title: "加载 m",
    bytecode: "method1@4: iload_1",
    sourceLine: "method1: int k = m + n;",
    sourceLineIndex: 7,
    bytecodeLine: "4: iload_1",
    bytecodeLineIndex: 13,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "1",
        locals: ["0: this=obj", "1: d"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
      {
        method: "App.method1()",
        pc: "4",
        locals: ["0: this=obj", "1: m=3", "2: n=4"],
        stack: ["m=3"],
        dynamicLink: "App.method1 -> CP",
        returnAddress: "return to method2@4",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "m1-5",
    title: "加载 n",
    bytecode: "method1@5: iload_2",
    sourceLine: "method1: int k = m + n;",
    sourceLineIndex: 7,
    bytecodeLine: "5: iload_2",
    bytecodeLineIndex: 14,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "1",
        locals: ["0: this=obj", "1: d"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
      {
        method: "App.method1()",
        pc: "5",
        locals: ["0: this=obj", "1: m=3", "2: n=4"],
        stack: ["m=3", "n=4"],
        dynamicLink: "App.method1 -> CP",
        returnAddress: "return to method2@4",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "m1-6",
    title: "执行加法",
    bytecode: "method1@6: iadd",
    sourceLine: "method1: int k = m + n;",
    sourceLineIndex: 7,
    bytecodeLine: "6: iadd",
    bytecodeLineIndex: 15,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "1",
        locals: ["0: this=obj", "1: d"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
      {
        method: "App.method1()",
        pc: "6",
        locals: ["0: this=obj", "1: m=3", "2: n=4"],
        stack: ["7"],
        dynamicLink: "App.method1 -> CP",
        returnAddress: "return to method2@4",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "m1-7",
    title: "保存 k",
    bytecode: "method1@7: istore_3",
    sourceLine: "method1: int k = m + n;",
    sourceLineIndex: 7,
    bytecodeLine: "7: istore_3",
    bytecodeLineIndex: 16,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "1",
        locals: ["0: this=obj", "1: d"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
      {
        method: "App.method1()",
        pc: "7",
        locals: ["0: this=obj", "1: m=3", "2: n=4", "3: k=7"],
        stack: [],
        dynamicLink: "App.method1 -> CP",
        returnAddress: "return to method2@4",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "m1-8",
    title: "加载 k",
    bytecode: "method1@8: iload_3",
    sourceLine: "method1: return k;",
    sourceLineIndex: 8,
    bytecodeLine: "8: iload_3",
    bytecodeLineIndex: 17,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "1",
        locals: ["0: this=obj", "1: d"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
      {
        method: "App.method1()",
        pc: "8",
        locals: ["0: this=obj", "1: m=3", "2: n=4", "3: k=7"],
        stack: ["7"],
        dynamicLink: "App.method1 -> CP",
        returnAddress: "return to method2@4",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "m1-9",
    title: "method1 返回",
    bytecode: "method1@9: ireturn",
    sourceLine: "method1: return k;",
    sourceLineIndex: 8,
    bytecodeLine: "9: ireturn",
    bytecodeLineIndex: 18,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "4",
        locals: ["0: this=obj", "1: d"],
        stack: ["7"],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2-2",
    title: "保存 i",
    bytecode: "method2@4: istore_2",
    sourceLine: "method2: int i = method1();",
    sourceLineIndex: 12,
    bytecodeLine: "4: istore_2",
    bytecodeLineIndex: 23,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "4",
        locals: ["0: this=obj", "1: d", "2: i=7"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2-3",
    title: "压入常量 5",
    bytecode: "method2@5: iconst_5",
    sourceLine: "method2: int j = 5;",
    sourceLineIndex: 13,
    bytecodeLine: "5: iconst_5",
    bytecodeLineIndex: 24,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "5",
        locals: ["0: this=obj", "1: d", "2: i=7"],
        stack: ["5"],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2-4",
    title: "保存 j",
    bytecode: "method2@6: istore_3",
    sourceLine: "method2: int j = 5;",
    sourceLineIndex: 13,
    bytecodeLine: "6: istore_3",
    bytecodeLineIndex: 25,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "6",
        locals: ["0: this=obj", "1: d", "2: i=7", "3: j=5"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2-5",
    title: "压入常量 6",
    bytecode: "method2@7: bipush 6",
    sourceLine: "method2: int k = 6 / d;",
    sourceLineIndex: 15,
    bytecodeLine: "7: bipush 6",
    bytecodeLineIndex: 26,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "7",
        locals: ["0: this=obj", "1: d", "2: i=7", "3: j=5"],
        stack: ["6"],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2-6",
    title: "加载 d",
    bytecode: "method2@9: iload_1",
    sourceLine: "method2: int k = 6 / d;",
    sourceLineIndex: 15,
    bytecodeLine: "9: iload_1",
    bytecodeLineIndex: 27,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "9",
        locals: ["0: this=obj", "1: d", "2: i=7", "3: j=5"],
        stack: ["6", "d"],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2-7",
    title: "执行除法",
    bytecode: "method2@10: idiv",
    sourceLine: "method2: int k = 6 / d;",
    sourceLineIndex: 15,
    bytecodeLine: "10: idiv",
    bytecodeLineIndex: 28,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "10",
        locals: ["0: this=obj", "1: d", "2: i=7", "3: j=5"],
        stack: ["6/d"],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2-8",
    title: "保存 k",
    bytecode: "method2@11: istore 4",
    sourceLine: "method2: int k = 6 / d;",
    sourceLineIndex: 15,
    bytecodeLine: "11: istore 4",
    bytecodeLineIndex: 29,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "11",
        locals: ["0: this=obj", "1: d", "2: i=7", "3: j=5", "4: k=6/d"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2-9",
    title: "跳转 return",
    bytecode: "method2@13: goto 26",
    sourceLine: "method2: return",
    sourceLineIndex: 19,
    bytecodeLine: "13: goto 26",
    bytecodeLineIndex: 30,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "13",
        locals: ["0: this=obj", "1: d", "2: i=7", "3: j=5", "4: k=6/d"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2-10",
    title: "method2 正常返回",
    bytecode: "method2@26: return",
    sourceLine: "method2: return",
    sourceLineIndex: 19,
    bytecodeLine: "26: return",
    bytecodeLineIndex: 36,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "20",
        locals: ["0: args", "1: obj", "2: d"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "main-12",
    title: "main 返回",
    bytecode: "main@20: return",
    sourceLine: "main: return",
    sourceLineIndex: 25,
    bytecodeLine: "20: return",
    bytecodeLineIndex: 51,
    stack: [],
  },
];

export const executionStepsException: ExecutionStep[] = [
  ...executionStepsNormal.slice(
    0,
    executionStepsNormal.findIndex((step) => step.id === "m2-7")
  ),
  {
    id: "m2x-0",
    title: "除法抛出异常",
    bytecode: "method2@10: idiv",
    sourceLine: "method2: int k = 6 / d;",
    sourceLineIndex: 15,
    bytecodeLine: "10: idiv",
    bytecodeLineIndex: 28,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d=0"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "10",
        locals: ["0: this=obj", "1: d=0", "2: i=7", "3: j=5"],
        stack: ["6", "0", "Exception"],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2x-1",
    title: "进入 catch，保存异常引用",
    bytecode: "method2@16: astore 4",
    sourceLine: "method2: catch (Exception e)",
    sourceLineIndex: 16,
    bytecodeLine: "16: astore 4",
    bytecodeLineIndex: 31,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d=0"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "16",
        locals: ["0: this=obj", "1: d=0", "2: i=7", "3: j=5", "4: e"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2x-2",
    title: "压入常量 7",
    bytecode: "method2@18: bipush 7",
    sourceLine: "method2: j = 7;",
    sourceLineIndex: 17,
    bytecodeLine: "18: bipush 7",
    bytecodeLineIndex: 32,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d=0"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "18",
        locals: ["0: this=obj", "1: d=0", "2: i=7", "3: j=5", "4: e"],
        stack: ["7"],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2x-3",
    title: "catch 中更新 j",
    bytecode: "method2@20: istore_3",
    sourceLine: "method2: j = 7;",
    sourceLineIndex: 17,
    bytecodeLine: "20: istore_3",
    bytecodeLineIndex: 33,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d=0"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "20",
        locals: ["0: this=obj", "1: d=0", "2: i=7", "3: j=7", "4: e"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2x-4",
    title: "加载异常引用",
    bytecode: "method2@21: aload 4",
    sourceLine: "method2: e.printStackTrace();",
    sourceLineIndex: 18,
    bytecodeLine: "21: aload 4",
    bytecodeLineIndex: 34,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d=0"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "21",
        locals: ["0: this=obj", "1: d=0", "2: i=7", "3: j=7", "4: e"],
        stack: ["e"],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2x-5",
    title: "打印异常栈",
    bytecode: "method2@23: invokevirtual printStackTrace",
    sourceLine: "method2: e.printStackTrace();",
    sourceLineIndex: 18,
    bytecodeLine: "23: invokevirtual #19",
    bytecodeLineIndex: 35,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "17",
        locals: ["0: args", "1: obj", "2: d=0"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
      {
        method: "App.method2(int)",
        pc: "23",
        locals: ["0: this=obj", "1: d=0", "2: i=7", "3: j=7", "4: e"],
        stack: [],
        dynamicLink: "App.method2 -> CP",
        returnAddress: "return to main@20",
        exceptionTable: "7..13 -> 16 (Exception)",
      },
    ],
  },
  {
    id: "m2x-6",
    title: "method2 返回",
    bytecode: "method2@26: return",
    sourceLine: "method2: return",
    sourceLineIndex: 19,
    bytecodeLine: "26: return",
    bytecodeLineIndex: 36,
    stack: [
      {
        method: "main([Ljava/lang/String;)",
        pc: "20",
        locals: ["0: args", "1: obj", "2: d=0"],
        stack: [],
        dynamicLink: "App.main -> CP",
        returnAddress: "JVM exit",
        exceptionTable: "none",
      },
    ],
  },
  {
    id: "main-12x",
    title: "main 返回",
    bytecode: "main@20: return",
    sourceLine: "main: return",
    sourceLineIndex: 25,
    bytecodeLine: "20: return",
    bytecodeLineIndex: 51,
    stack: [],
  },
];
